### ISSUE TITLE
There is an issue using Get-WslDistribution

### ISSUE THREAD

**Issue by patrick330602** [tylerl0706/PSWsl#17]
It seems that it has trouble displaying the distribution properly:

![image](https://user-images.githubusercontent.com/15316889/39457488-de931e44-4cb3-11e8-8f55-0ee5a4c0a298.png)

I am using Windows 10 build 17134.5 right now.

**Comment by tylerl0706** [comment]
Thanks for this! This is likely a dupe of #12... Are you using Windows PowerShell? If you run:

```
$a = wslconfig /l
$a
```

does it look funky?

**Comment by patrick330602** [comment]
@tylerl0706 Yep, it looks like there are spaces between each character

**Comment by tylerl0706** [comment]
Yeah - If you try it on PSCore, it should be better. The problem is this line: 

https://github.com/tylerl0706/PSWsl/blob/master/PSWsl.psm1#L160

Which works on PSCore but not Windows PowerShell :( 

I'll dupe my issue to yours since you have an image :)

**Comment by patrick330602** [comment]
Well, find a way which (kind of) works:
![image](https://user-images.githubusercontent.com/15316889/43903141-54ba720c-9c1e-11e8-8019-5ddf395be886.png)

the code is here:
```powershell
[System.Text.Encoding]::Unicode.GetString([System.Text.Encoding]::UTF8.GetBytes((wslconfig.exe /l))) -split '\s\s+' | Select-Object -Skip 1 -Unique
```

**Comment by patrick330602** [comment]
I will close this as it is merged
