### ISSUE TITLE
Tests are written with a presumed configuration in mind

### ISSUE THREAD

**Issue by rbeesley** [tylerl0706/PSWsl#6]
These tests will fail depending upon what system they are being tested on. This is perhaps an extension of the other issue, regarding how to run tests in CI, but I felt the need to disclose why it is a problem and that it exists outside CI.

**Comment by tylerl0706** [comment]
Yep same issue. I was trying to mock wslconfig here:
https://github.com/tylerl0706/PSWsl/blob/master/test/PSWsl.Tests.ps1#L11

But the encoding of the output of the actual wslconfig is messing with me.

**Comment by tylerl0706** [comment]
Duping this to #3
